// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: internal/proto/agent.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StreamResponse_NodeStatus int32

const (
	StreamResponse_Started StreamResponse_NodeStatus = 0
	StreamResponse_Failed  StreamResponse_NodeStatus = 1
)

// Enum value maps for StreamResponse_NodeStatus.
var (
	StreamResponse_NodeStatus_name = map[int32]string{
		0: "Started",
		1: "Failed",
	}
	StreamResponse_NodeStatus_value = map[string]int32{
		"Started": 0,
		"Failed":  1,
	}
)

func (x StreamResponse_NodeStatus) Enum() *StreamResponse_NodeStatus {
	p := new(StreamResponse_NodeStatus)
	*p = x
	return p
}

func (x StreamResponse_NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResponse_NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_agent_proto_enumTypes[0].Descriptor()
}

func (StreamResponse_NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_agent_proto_enumTypes[0]
}

func (x StreamResponse_NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResponse_NodeStatus.Descriptor instead.
func (StreamResponse_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{0, 0}
}

type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//	*StreamResponse_NodeStatus_
	//	*StreamResponse_Event_
	Resp isStreamResponse_Resp `protobuf_oneof:"resp"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (m *StreamResponse) GetResp() isStreamResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *StreamResponse) GetNodeStatus() StreamResponse_NodeStatus {
	if x, ok := x.GetResp().(*StreamResponse_NodeStatus_); ok {
		return x.NodeStatus
	}
	return StreamResponse_Started
}

func (x *StreamResponse) GetEvent() *StreamResponse_Event {
	if x, ok := x.GetResp().(*StreamResponse_Event_); ok {
		return x.Event
	}
	return nil
}

type isStreamResponse_Resp interface {
	isStreamResponse_Resp()
}

type StreamResponse_NodeStatus_ struct {
	NodeStatus StreamResponse_NodeStatus `protobuf:"varint,1,opt,name=nodeStatus,proto3,enum=proto.StreamResponse_NodeStatus,oneof"`
}

type StreamResponse_Event_ struct {
	Event *StreamResponse_Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*StreamResponse_NodeStatus_) isStreamResponse_Resp() {}

func (*StreamResponse_Event_) isStreamResponse_Resp() {}

type CreateServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *NodeSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceRequest) GetSpec() *NodeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{2}
}

type StreamResponse_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamResponse_Event) Reset() {
	*x = StreamResponse_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse_Event) ProtoMessage() {}

func (x *StreamResponse_Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse_Event.ProtoReflect.Descriptor instead.
func (*StreamResponse_Event) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StreamResponse_Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_agent_proto protoreflect.FileDescriptor

var file_internal_proto_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb,
	0x01, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x21, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x10, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x3b, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xcb, 0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x02, 0x44, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_agent_proto_rawDescOnce sync.Once
	file_internal_proto_agent_proto_rawDescData = file_internal_proto_agent_proto_rawDesc
)

func file_internal_proto_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_agent_proto_rawDescData)
	})
	return file_internal_proto_agent_proto_rawDescData
}

var file_internal_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_agent_proto_goTypes = []interface{}{
	(StreamResponse_NodeStatus)(0), // 0: proto.StreamResponse.NodeStatus
	(*StreamResponse)(nil),         // 1: proto.StreamResponse
	(*CreateServiceRequest)(nil),   // 2: proto.CreateServiceRequest
	(*CreateRequestResponse)(nil),  // 3: proto.CreateRequestResponse
	(*StreamResponse_Event)(nil),   // 4: proto.StreamResponse.Event
	(*NodeSpec)(nil),               // 5: proto.NodeSpec
	(*empty.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_internal_proto_agent_proto_depIdxs = []int32{
	0, // 0: proto.StreamResponse.nodeStatus:type_name -> proto.StreamResponse.NodeStatus
	4, // 1: proto.StreamResponse.event:type_name -> proto.StreamResponse.Event
	5, // 2: proto.CreateServiceRequest.spec:type_name -> proto.NodeSpec
	6, // 3: proto.AgentService.Do:input_type -> google.protobuf.Empty
	2, // 4: proto.AgentService.CreateService:input_type -> proto.CreateServiceRequest
	6, // 5: proto.AgentService.Stream:input_type -> google.protobuf.Empty
	6, // 6: proto.AgentService.Do:output_type -> google.protobuf.Empty
	3, // 7: proto.AgentService.CreateService:output_type -> proto.CreateRequestResponse
	1, // 8: proto.AgentService.Stream:output_type -> proto.StreamResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_proto_init() }
func file_internal_proto_agent_proto_init() {
	if File_internal_proto_agent_proto != nil {
		return
	}
	file_internal_proto_structs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_agent_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StreamResponse_NodeStatus_)(nil),
		(*StreamResponse_Event_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_proto_depIdxs,
		EnumInfos:         file_internal_proto_agent_proto_enumTypes,
		MessageInfos:      file_internal_proto_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_proto = out.File
	file_internal_proto_agent_proto_rawDesc = nil
	file_internal_proto_agent_proto_goTypes = nil
	file_internal_proto_agent_proto_depIdxs = nil
}
